create table tb001_user (a001_id int8 generated by default as identity, a001_email varchar(255), a001_name varchar(255), a001_password varchar(255), primary key (a001_id));
create table tb002_role (a002_id int8 generated by default as identity, a002_role_name varchar(255), primary key (a002_id));
create table tb003_user_role (a001_user_id int8 not null, a002_role_id int8 not null, primary key (a001_user_id, a002_role_id));
alter table if exists tb001_user add constraint UK_96uyjh9vmet8tm0q8sa73jwv6 unique (a001_email);
alter table if exists tb003_user_role add constraint FKh3n8qaou7vl4mtu3lrixia7c7 foreign key (a002_role_id) references tb002_role;
alter table if exists tb003_user_role add constraint FKsxpi019vykxml9nrf4bknul77 foreign key (a001_user_id) references tb001_user;
